package poseidon.DTO._Interfaces;

public interface IKomment {
//    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
//    poszt_id NUMBER NOT NULL,
//    PS_kod VARCHAR(20) NOT NULL,
//    tartalom VARCHAR(200)
}
