package poseidon.DTO._Interfaces;

public interface IKurzus {
//    id NUMBER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
//    nev VARCHAR2(50) NOT NULL,
//    oktato_PS_kod VARCHAR2(20) NOT NULL,
//    kezdes_ideje_nap VARCHAR2(15) NOT NULL,
//    kezdes_ideje_idopont TIMESTAMP NOT NULL,
//    tantargy_id NUMBER NOT NULL,
//    terem_id NUMBER NOT NULL,
//    felveheto CHAR(1) NOT NULL,
//    vizsga CHAR(1) NOT NULL
}
